### ISSUE TITLE
Batch Export Functionality is not working properly using Angular FusionCharts component 3.0.2 

### ISSUE THREAD

**Issue by soumyasdutta** [fusioncharts/angular-fusioncharts#59] opened 2019-06-12 11:58 UTC
The Batch Export functionality is not working properly. Please check the following sample https://codesandbox.io/s/angular-j6kkt here for the first time the batch export functionality is working properly but after making certain changes in component.ts file after auto reloads the number of charts getting increased in the exported image.

**Comment by yakuzaaaa** [comment] 2019-07-23 04:39
charts in batchExport object accepts array of chart object which the above sample is passing by FusionCharts.items
Due to hot loading, the old FusionCharts object is not destroyed and thus items array has the old charts also. @rohanoid5 So, is this is a bug?

**Comment by rohanoid5** [comment] 2019-07-23 04:48
@yakuzaaaa yes, that is a bug. `FusionCharts.items` should hold the same number of instances as the  number of `angular-fusioncharts` component.

**Comment by yakuzaaaa** [comment] 2019-10-17 12:16
@soumyasdutta This seems to be issue with codesandbox iframe reload. Closing this issue as its not a bug related to our angular-wrapper.

**Closed by yakuzaaaa** 2019-10-17 12:16 UTC

**Comment by jimut** [comment] 2019-10-17 12:23
This message serves as confirmation that you are now successfully registered in our support center.

Registered Email: reply@reply.github.com
Password: 479k854pcm

You can visit the Support Desk at any time by going to http://help.fusioncharts.com/

Please do let us know if you have any questions.

Regards,


FusionCharts Team
------------------------------------------------------
Support Center: http://help.fusioncharts.com/index.php?

**Comment by jimut** [comment] 2019-10-17 12:23
Dear fusioncharts/angular-fusioncharts,

Thanks for your mail and interest in FusionCharts suite of products.

This is an automated response to let you know that we've received your request. Our support staff is currently reviewing it, and would get in touch with you soon. Meanwhile, you may use our self-help options like Community Forums, Knowledge base & Online Documentation at http://support.fusioncharts.com/

Please note the information below, as it will allow you to track the progress of your request online.

	Ticket ID: 330357
	Subject: Re: [fusioncharts/angular-fusioncharts] Batch Export Functionality is not working properly using Angular FusionCharts component 3.0.2  (#59)
	Department: General
	Type: Issue
	Status: Open
	Priority: Medium

You can check the status of or reply to this ticket online at: http://help.fusioncharts.com/index.php?/Tickets/Ticket/View/330357

Thanks,

FusionCharts Team


------------------------------------------------------
Support Center: http://help.fusioncharts.com/index.php?
